apiVersion: v1
kind: Namespace
metadata:
  name: mongo
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongo
type: Opaque #default (key value)
data:
  mongo-root-username: dXNlcm5hbWVXb29k
  mongo-root-password: cGFzc3dvcmRXb29k
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mongo
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.2
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret #name from secret.yml
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret 
              key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongo
spec:
  selector:
    app: mongodb #same as lable pod
  ports:
    - protocol: TCP
      port: 27017 #could be differrent
      targetPort: 27017 #pod port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: mongo
data:
  database_url: mongodb-service #name of the service of mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: mongo
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME #same as mongoDB
          valueFrom:
            secretKeyRef:
              name: mongodb-secret 
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret 
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: #from configmap
            configMapKeyRef:
              name: mongodb-configmap #name from fonfigmap
              key: database_url #key (url) from fonfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongo
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000 #port that will be open on external ip. 
#Range between 30000-32767